server:
  port: 8080


spring:
  datasource:
    url: jdbc:mysql://localhost:3306/dotpay
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: Sintax80



  main:
    banner-mode: off



  mvc:
    throw-exception-if-no-handler-found: true
  web:
    resources:
      add-mappings: false

  jpa:
    show-sql: true
    database-platform: org.hibernate.dialect.MySQL8Dialect
    hibernate:
      ddl-auto: update



